NAME = prg05_11
PATH = p:\Assembler\masm32\bin
PLIB = p:\Assembler\masm32
#NAMERES=prg05_11
OBJS = $(NAME).obj
#DEF  = $(NAME).def
#RES = $(NAMERES).res

!if $d(DEBUG)
TASMDEBUG=/zi
LINKDEBUG=/v
!else
TASMDEBUG=
LINKDEBUG=
!endif

!if $d(MAKEDIR)
#IMPORT=$(MAKEDIR)\import32+maket_dll
IMPORT=import32
!else
#IMPORT=import32+maket_dll
IMPORT=import32
!endif

$(NAME).EXE: $(OBJS) $(DEF) $(RES)
#  tlink32 /Tpe /aa /c  /v $(LINKDEBUG) $(OBJS),$(NAME),, $(IMPORT), $(DEF),prg_3.RES
   $(PATH)\link /SUBSYSTEM:WINDOWS /LIBPATH:$(PLIB)\lib $(NAME).obj 

.asm.obj:
   $(PATH)\ml /c /coff /Cp $&.asm

